version: '3'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-php5.6
    image: docker-php5.6
    volumes:
        - ./html:/var/www/html:delegated
    ports:
      - 8080:80
    network_mode: bridge