version: '3'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-php5.6
    image: docker-php5.6
    volumes:
        - /Users/desenvolvimento/Sites:/var/www/html
    ports:
      - 8000:80
    network_mode: bridge